### PR TITLE
SLING-12410 ResourceResolver: Add impl for copy and move methods

### PR DESCRIPTION
**Pull request by senn**
https://issues.apache.org/jira/browse/SLING-12410

### CODE REVIEW

**Comment by senn** [comment]
I did not create a SLING issue yet... If this looks somewhat acceptable, I can do that ofcourse.

**Comment by stefanseifert** [comment]
looks very good, thanks!

yes, we always need a SLING ticket - i've created one for this ticket: https://issues.apache.org/jira/browse/SLING-12410

**Review by stefanseifert — APPROVED** [review]

**Comment by senn** [comment]
Hey @stefanseifert, thanks for the fast merge.  Any chance of a fast release of this?  Or maybe an indication when the next version would normally be released?

**Comment by stefanseifert** [comment]
i plan to do start the release process on all pending sling mocks modules this week - calculating in the voting period you can expect a release in public early next week

**Pull request merged**
