### PR TITLE
SLING-11053 implement support for getPropertyMap

### PR DESCRIPTION
**Pull request by joerghoh**
I just copied over the code from the implementation, seems to be the easiest way.

### CODE REVIEW

**Review by stefanseifert — CHANGES_REQUESTED** [review]
lgtm - can you also add a simple test case?

**Comment by joerghoh** [comment]
I have a test ready, but it requires an update of the Sling API dependency to 2.24.0 (currently there is a managed dependency version of 2.16.4). Not sure if this is a good idea ...

**Comment by stefanseifert** [comment]
optimally we could keep the current older dependencies - i always try to make sure sling-mock and resourceresolver-mock can also be used for projects that are not using the latest up-to-date dependencies.

**Comment by joerghoh** [comment]
As I want to implement a method coming with Sling 2.24.0, I need to add a dependency to it. Otherwise I can try to avoid using the ```org.apache.sling.api.resource.ResourceResolver``` interface in tests and do just a cast to the ```MockResourceResolver```.

**Comment by stefanseifert** [comment]
yes, just use MockResourceResolver, that's fine for the test

**Review by stefanseifert — APPROVED** [review]

**Pull request merged**
